### ISSUE TITLE
Need to create services foreach

### ISSUE THREAD

**Issue by proneetv** [proneetv/ariaDB#1]
- database
- running indexer
- caching layer
- file handling stuff
- network layer/warp 
- api layer

**Comment by 2020saurav** [comment]
We are having single index (B+ Tree) on the data store, so I am keeping the values in the leaves. I am not anticipating any other (better) indexer for our use case of 1-D keys. So, the database and the indexer are interwined together.

Caching layer: creating a separate issue. @proneetv 

File handling stuff : done in database+indexer

Network (Warp) : done. code for handling deletion needs to be added. creating a separate issue @proneetv 

API layer : done. `src/Library` deletion needs to be handled.
