### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by 2020saurav** [proneetv/ariaDB#10]
Configure cabal test suite for automated testing. Use exitcode-stdio-1.0 or other type.
Add the project in travis ci as well :smile:

**Comment by proneetv** [comment]
https://github.com/proneetv/ariaDB/commit/f6222c6ad6b4921e5fca9c793f4a6d1c0431e468 & https://github.com/proneetv/ariaDB/commit/8ad307b5468b01ae82d2dfc9ae756b97606f40c1 fixes this, test files need to be written as the `exitcode-stdio` expects otherwise tests will always pass! :stuck_out_tongue:
