### ISSUE TITLE
B+ Tree TODOs

### ISSUE THREAD

**Issue by proneetv** [proneetv/ariaDB#2]
B+ Tree DS in Haskell

**Comment by 2020saurav** [comment]
Much of it has been done today.
## TODO:
- Resolving TODOs written in code. Mostly in finding correct position to insert values
- `findKey` operation : easy
- add exports in modules
- test with warp

**Comment by 2020saurav** [comment]
Correct position to insert ✓
findKey ✓

**Comment by 2020saurav** [comment]
add exports in modules of BPT ✓
test with warp (get and post) ✓
