### ISSUE TITLE
Make storage efficient in terms of redundant information being saved on disk

### ISSUE THREAD

**Issue by proneetv** [proneetv/ariaDB#4]
@2020saurav can you please suggest a few sane techniques to go forward with this?

**Comment by 2020saurav** [comment]
- File size be made in multiples of disk page size.
- Not storing redundant data such as `AriaKey` or `AriaValue` etc. But this will make it harder to parse the content. Presently, I am using `read` and `show`, which is cool.
- Compression (must be reversible)

**Comment by 2020saurav** [comment]
*May not implement this*
