### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by 2020saurav** [proneetv/ariaDB#9]
- Write comments and documentations
- Complete readme and Wiki

**Comment by 2020saurav** [comment]
comments and documentations ✓

**Comment by 2020saurav** [comment]
@proneetv Complete readme and Wiki

**Comment by proneetv** [comment]
https://github.com/proneetv/ariaDB/commit/da0eeb583dd539f35cc93b3b32901e74fb379876 takes care of this issue!
